### ISSUE TITLE
uninitialized constant Sidekiq::Job with Sidekiq 6.2.2

### ISSUE THREAD

**Issue by bmulholland** [carwow/honeykiq#22]
https://github.com/mperham/sidekiq/issues/4973

https://github.com/mperham/sidekiq/blob/master/Changes.md#622

Result:
NameError
uninitialized constant Sidekiq::Job
honeykiq (1.3.0) lib/honeykiq/server_middleware.rb in call at line 11

https://github.com/carwow/honeykiq/blob/master/lib/honeykiq/server_middleware.rb#L11

**Comment by PChambino** [comment]
Thanks for the reminder @bmulholland  We are also fixing this internally. Released on v1.4.0.
Let me know if there are any other issues.

**Comment by bmulholland** [comment]
Confirmed fixed - thanks!
