### ISSUE TITLE
Database queries are not linked to their job

### ISSUE THREAD

**Issue by DanielHeath** [carwow/honeykiq#8]
In [server_middleware.rb](https://github.com/carwow/honeykiq/blob/master/lib/honeykiq/server_middleware.rb#L10) a new event is created, but as it's not done via `start_span` anything else you instrument (eg database queries, AWS service use) is not linked to the event.

Is there a reason to use `libhoney` instead of `honeycomb-beeline`? PRs accepted?

**Comment by PChambino** [comment]
We have our own custom setup because the beeline was not as full-featured is it is now when we started using Honeycomb.

I agree that supporting the beeline would be better, but we still would like to have support for using the libhoney client directly.

**Comment by PChambino** [comment]
@DanielHeath Release beeline support on v1.1.0. Let me know if that matches your expectations.
